[workspace]
members = [
    "rs/canister",
    "rs/canister/src/canister/types",
    "rs/lambda",
    "rs/types"
]
resolver = "3"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.18"
serde = "1"
