[workspace]
members = [
    "rs/canister",
    "rs/canister/core",
    "rs/canister/types",
    "rs/constants",
    "rs/lambda",
    "rs/lambda/canister_client",
    "rs/lambda/core",
    "rs/types"
]
resolver = "3"

[workspace.dependencies]
candid = "0.10"
ic-agent = "0.44.0"
ic-cdk = "0.18"
ic_principal = "0.1.1"
serde = "1"
