[package]
name = "one_sec_deposit_notifier_canister"
version = "0.1.0"
edition = "2024"

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
serde = { version = "1.0.219", features = ["derive"] }
